minisocialsite/minisocialsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^groups/', include('groups.urls', namespace='groups')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
]

minisocialsite/posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.PostList.as_view(), name='all'),
    url(r'^new/$', views.CreatePost.as_view(), name='create'),
    url(r'^by/(?P<username>[-\w]+)/$', views.UserPosts.as_view(), name='for_user'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetail.as_view(), name='single'),
    url(r'^delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete'),

]

minisocialsite/groups/models.py
from django.db import models
from django.utils.text import slugify
from django.core.urlresolvers import reverse

# Create your models here.
import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey(Group)
    user = models.ForeignKey(User)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

minisocialsite/posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings

import misaka

from groups.models import Group, GroupMember
# Create your models here.

from django.contrib.auth import get_user_model
User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts')
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name='posts', null=True, blank=True)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug':self.group.slug})
        #return reverse('posts:single', kwargs={'username':self.user.username,'pk':self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'message']

minisocialsite/posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ('user','message', 'group')

minisocialsite/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from django.http import Http404
from django.contrib import messages

from braces.views import SelectRelatedMixin

from . import models
from .forms import PostForm
from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()
# Create your views here.

class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ('user', 'group')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_groups'] = Group.objects.all()

        return context


class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))

        except User.DoesNotExist:
            raise Http404

        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = User.username
        context['all_groups'] = Group.objects.all()
        return context

class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    model = models.Post
    fields = ('message','group')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)



class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)

minisocialsite/posts/templates/posts/_post.html
<div class="post media">
  <h3 id="post_message">{{post.message_html|safe}}</h3>
  <div class="media-body">
    <!-- <strong>{{ post.user.username }}</strong> -->
    <h5 class='media-heading'>
    <span class="username">
      <a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a>
    </span>
    <time class='time'>
      <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a>
    </time>
    </h5>

    <div class="media-footer">
      {% if user.is_authenticated and post.user == user %}
      <a href="{% url 'posts:delete' pk=post.pk %}" title='delete' class='btn btn-simple'>
        <span class="glyphicon glyphicon-remove text-danger" aria-hidden='true'></span>
        <span class="tetx-danger icon-label">Delete</span>
      </a>
      {% endif %}
    </div>
  </div>

</div>

minisocialsite/posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
<div class="posts-page">
  <div class="container">
    <div class="row">
      {% block prepost %}{% endblock %}
      {% block post_content %}{% endblock %}
      {% block postpost %}{% endblock %}

    </div>

  </div>

</div>
{% endblock %}

minisocialsite/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}
{% block post_content %}
<h3>Are you sure you want to delete this reply?</h3>

<div class="posts">
  {% include "posts/_post.html" with post=object hide_delete=True %}
</div>

<form method="post">
  {% csrf_token %}
  <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
  <a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-simple btn-large btn-default">Cancel</a>

</form>

{% endblock %}

minisocialsite/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}
{% block post_content %}

<div class="col-md-8">
  {% include "posts/_post.html" %}
</div>

{% endblock %}

minisocialsite/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap3 %}

{%  block post_content %}

<h3>Post a new reply</h3>
<form action="{% url 'posts:create' %}" method="post" id="postForm">
  <div class="form-group">
    {% csrf_token %}
    <!-- <label for="reply">Reply:</label>
    <textarea class="form-control" rows="5" id="reply"></textarea>

    <label for="thread">Threads:</label>
    <select class="form-control" id="threads">
      {% for member in user.group_set.all %}
      <option>{{ member.name }}</option>
      {% endfor %}
    </select> -->
    {% bootstrap_field form.message %}
    {% bootstrap_field form.group label='Threads' %}
  </div>

  <input type="submit" class="btn btn-primary btn-large" value="Post">

</form>
{% endblock %}

minisocialsite/posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}
{% block prepost %}

<div class="col-md-4">
  {% if request.user.is_authenticated %}
  <div class="card card-with-shadow">
    <div class="content">
      <h5 class='title' style="font-size:20px;">Your Following Threads</h5>
      <ul class='list-unstyled'>
        {% for member in user.group_set.all %}
        <li class='group li-with-bullet'>
          <a href="{% url 'groups:single' slug=member.slug %}">{{ member.name }}</a>
        </li>
        {% endfor %}

      </ul>

    </div>

  </div>
  {% endif %}

  <div class="card card-with-shadow">
    <div class="content">
      <h5 class="title"  style="font-size:20px;">All Threads</h5>
      <ul class="list-unstyled">
        {% for other_group in all_groups %}
        <li class="group li-with-bullet">
          <a href="{% url 'groups:single' slug=other_group.slug %}">{{ other_group.name }}</a>
        </li>

        {% endfor %}
      </ul>

    </div>

  </div>

</div>

{% endblock %}

{% block post_content %}
<div class="col-md-8">
  {% for post in post_list %}
    {% include "posts/_post.html" %}
  {% endfor %}

</div>
{% endblock %}

minisocialsite/posts/templates/posts/user_posts_list.html
{% extends "posts/post_base.html" %}
{% block prepost %}

<div class="col-md-4">
  <h1>@{{post_user.username}}</h1>
</div>

{% endblock %}

{% block post_content %}
<div class="col-md-8">
  {% for post in post_list %}
  {% include "posts/_post.html" %}
  {% endfor %}

</div>

{% endblock %}