minisocialsite/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib import admin
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'signup/$', views.SignUp.as_view(), name='signup'),
    url(r'login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'logout/$', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),

]

minisocialsite/minisocialsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^groups/', include('groups.urls', namespace='groups')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
]

minisocialsite/posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.PostList.as_view(), name='all'),
    url(r'^new/$', views.CreatePost.as_view(), name='create'),
    url(r'^by/(?P<username>[-\w]+)/$', views.UserPosts.as_view(), name='for_user'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetail.as_view(), name='single'),
    url(r'^delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete'),

]

minisocialsite/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Micro Forum</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css" integrity="sha384-PmY9l28YgO4JwMKbTvgaS7XNZJ30MK9FAZjjzXtlqyZCqBY6X6bXIkM++IkyinN+" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css" integrity="sha384-jzngWsPS6op3fgRCDTESqrEJwRKck+CILhJVO5VvaAZCq8JYf8HsR/HPpBOOPZfR" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js" integrity="sha384-vhJnz1OVIdLktyixHY4Uk3OHEwdQqPppqYR8+5mjsauETgLOcEynD9oPHhhz18Nw" crossorigin="anonymous"></script>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Secular+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Play" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Julius+Sans+One" rel="stylesheet">


    <!-- Master Css -->
    <link rel="stylesheet" href="{% static 'css/master.css' %}">


  </head>
  <body>

    <nav class='navbar fixed-top mynav' role='navigation' id='navbar' style="background-color: #b2b2b2;">

      <div class="container">

        <ul class='nav navbar-nav' >
            <li><a class='navbar-brand' id="bigbrand" href="{% url 'home' %}">Micro Forum</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><a id='navft' href="{% url 'posts:for_user' username=user.username %}">My Posts</a></li>
            <li><a id='navft' href="{% url 'posts:create' %}">New Reply</a></li>
            <li><a id='navft' href="{% url 'groups:all' %}">Threads</a></li>
            <li><a id='navft' href="{% url 'groups:create' %}">New Thread</a></li>
            <li><a id='navft' href="{% url 'accounts:logout' %}">Log Out</a></li>
        </ul>

        <ul class="nav navbar-nav">
          {% else %}
            <li><a href="{% url 'groups:all' %}">Threads</a></li>
            <li><a href="{% url 'accounts:login' %}">Log In</a></li>
            <li><a href="{% url 'accounts:signup'%}">Sign Up</a></li>
        </ul>
          {% endif %}


      </div>

    </nav>

    <div class="container mycontent">

      {% block content %}


      {% endblock %}

    </div>

  </body>
  <script type="text/javascript" src="{% static 'minisocialsite/js/master.js' %}">

  </script>
</html>

minisocialsite/templates/index.html
{% extends "base.html" %}
{% block content %}

<h1>Welcome to Micro Forum!</h1>

<div class="container header">
   <div class="subc">
      <div class="bg"></div>
   </div>
</div>

{% endblock %}

minisocialsite/templates/test.html
{% extends "base.html" %}
{% block content %}

<h1>You are now logged in!</h1>

{% endblock%}

minisocialsite/templates/thanks.html
{% extends "base.html" %}
{% block content %}

<h1>Thanks for visiting, come back soon!</h1>

{% endblock%}